# fly.toml app configuration file generated for gdq-stats-staging on 2023-05-23T19:15:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gdq-stats-staging"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]
  [build.args]
    BP_GO_TARGETS = "./cmd/server"

[env]
  APPLICATION_PORT = "4000"
  BASE_URL = "staging.api.gdq-stats.tricirc.de"
  RUNTIME_ENV = "staging"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
