# https://taskfile.dev

version: "3"

dotenv:
  - ".env.development"

tasks:
  default:
    desc: Runs task dev
    cmds:
      - task: dev

  dev:
    desc: Start the server in development mode
    cmds:
      - air

  graphql-generate:
    cmds:
      - go run github.com/99designs/gqlgen generate

  migrate-new:
    desc: Create migration files for name=$1
    cmds:
      - migrate create -seq -ext=.sql -dir=./migrations {{.name}}

  migrate-up:
    desc: Apply all database migrations
    cmds:
      - migrate -path ./migrations -database $MIGRATE_DATABASE_URL up

  migrate-down:
    desc: Revert all database migrations
    cmds:
      - migrate -path ./migrations -database $MIGRATE_DATABASE_URL down

  migrate-down-to:
    desc: Revert database migration down to version=$1
    cmds:
      - migrate -path ./migrations -database $MIGRATE_DATABASE_URL down {{.version}}

  migrate-force:
    desc: Force database migration to version=$1
    cmds:
      - migrate -path ./migrations -database $MIGRATE_DATABASE_URL force {{.version}}
