package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/rfermann/gdq-stats-backend/internal/gql"
	"github.com/rfermann/gdq-stats-backend/internal/models"
)

// EventType is the resolver for the eventType field.
func (r *eventResolver) EventType(ctx context.Context, obj *models.Event) (*models.EventType, error) {
	return r.Services.EventTypesService.GetEventTypeByID(obj.EventTypeID)
}

// CreateEvent is the resolver for the createEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, input gql.CreateEventInput) (*models.Event, error) {
	return r.Services.EventsService.CreateEvent(input)
}

// AggregateEventStatistics is the resolver for the aggregateEventStatistics field.
func (r *mutationResolver) AggregateEventStatistics(ctx context.Context, input *gql.AggregateEventStatisticsInput) (*models.Event, error) {
	return r.Services.EventsService.AggregateEventStatistics(input)
}

// GetAlternativeEvents is the resolver for the getAlternativeEvents field.
func (r *queryResolver) GetAlternativeEvents(ctx context.Context) ([]*models.Event, error) {
	return r.Services.EventsService.GetAlternativeEvents()
}

// GetCurrentEvent is the resolver for the getCurrentEvent field.
func (r *queryResolver) GetCurrentEvent(ctx context.Context) (*models.Event, error) {
	return r.Services.EventsService.GetCurrentEvent()
}

// GetEvents is the resolver for the getEvents field.
func (r *queryResolver) GetEvents(ctx context.Context) ([]*models.Event, error) {
	return r.Services.EventsService.GetEvents()
}

// Event returns gql.EventResolver implementation.
func (r *Resolver) Event() gql.EventResolver { return &eventResolver{r} }

type eventResolver struct{ *Resolver }
