package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/rfermann/gdq-stats-backend/internal/gql"
	"github.com/rfermann/gdq-stats-backend/internal/models"
)

// MigrateEventData is the resolver for the migrateEventData field.
func (r *mutationResolver) MigrateEventData(ctx context.Context, input gql.MigrateEventDataInput) (*models.Event, error) {
	return r.Services.EventsService.MigrateEventData(input)
}

// GetEventData is the resolver for the getEventData field.
func (r *queryResolver) GetEventData(ctx context.Context, input *gql.GetEventDataInput) (*gql.EventDataResponse, error) {
	return r.Services.EventsService.GetEventData(input)
}
