package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"

	db_models "github.com/rfermann/gdq-stats-backend/internal/db/models"
	"github.com/rfermann/gdq-stats-backend/internal/gql"
)

// GetCurrentEvent is the resolver for the getCurrentEvent field.
func (r *queryResolver) GetCurrentEvent(ctx context.Context) (*db_models.Event, error) {
	return r.Services.EventService.GetCurrentEvent()
}

// Query returns gql.QueryResolver implementation.
func (r *Resolver) Query() gql.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
