package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/rfermann/gdq-stats-backend/internal/gql"
	"github.com/rfermann/gdq-stats-backend/internal/models"
)

// MigrateGames is the resolver for the migrateGames field.
func (r *mutationResolver) MigrateGames(ctx context.Context, input gql.MigrateGamesInput) ([]*models.Game, error) {
	return r.Services.GamesService.CreateGames(input)
}

// GetGames is the resolver for the getGames field.
func (r *queryResolver) GetGames(ctx context.Context, input *gql.GetEventInformationInput) ([]*models.Game, error) {
	return r.Services.GamesService.GetGames(input)
}
