// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db_models

var TableNames = struct {
	EventData        string
	EventTypes       string
	Events           string
	Games            string
	SchemaLock       string
	SchemaMigrations string
}{
	EventData:        "event_data",
	EventTypes:       "event_types",
	Events:           "events",
	Games:            "games",
	SchemaLock:       "schema_lock",
	SchemaMigrations: "schema_migrations",
}
